spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot-demo?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
magic:
  id:
    database:
      step: 1
      retry-times: 3
      table-name: id_test